# Generated by Django 2.0.7 on 2018-07-03 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('destination', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTS.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('admin_status', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTS.Office')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(default='staff', max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTS.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTS.Office'),
        ),
    ]
