# Generated by Django 2.0.7 on 2018-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTS', '0002_auto_20180705_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileslogs',
            old_name='action',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='filetracker',
            name='file_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='filetracker',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
