# Generated by Django 2.0.7 on 2018-07-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTS', '0003_auto_20180705_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileslogs',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileslogs',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileslogs',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filetracker',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filetracker',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filetracker',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
