# Generated by Django 2.0.7 on 2018-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTS', '0005_auto_20180711_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='management_status',
            field=models.BooleanField(default=False),
        ),
    ]
