# Generated by Django 2.0.7 on 2018-10-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTS', '0006_staff_management_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stafflogin',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
