# Generated by Django 2.0.7 on 2018-10-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FTS', '0007_auto_20181012_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflogin',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTS.Staff', unique=True),
        ),
    ]
