# Generated by Django 2.0.6 on 2018-07-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='', null=True)),
                ('status', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='', null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fts.department')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fts.office'),
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fts.office'),
        ),
    ]
